"""RFC 7807 Problem Details representation for HTTP APIs.

Provides structured error payloads across REST endpoints and SSE error frames:
{
    "type": "urn:geoai:error:400",
    "title": "Bad Request",
    "status": 400,
    "detail": "...",
    "instance": "/api/...",
    "error": { ... }
}
"""

from __future__ import annotations

from http import HTTPStatus
from typing import Any, Mapping
from pydantic import BaseModel, ConfigDict, Field


def get_http_title(status_code: int) -> str:
    try:
        return HTTPStatus(status_code).phrase
    except ValueError:
        return "Internal Error" if status_code >= 500 else "Client Error"


class ProblemDetails(BaseModel):
    """Problem Details object conforming to RFC 7807."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    type: str = Field(
        default="about:blank",
        description="A URI reference that identifies the problem type.",
    )
    title: str = Field(
        default="An error occurred",
        description="A short, human-readable summary of the problem type.",
    )
    status: int = Field(
        default=500,
        description="The HTTP status code generated by the origin server.",
    )
    detail: str = Field(
        ...,
        description="A human-readable explanation specific to this occurrence.",
    )
    instance: str | None = Field(
        default=None,
        description="A URI reference that identifies the specific occurrence.",
    )

    @classmethod
    def from_status(
        cls,
        status_code: int,
        detail: str,
        instance: str | None = None,
        type_uri: str | None = None,
        title: str | None = None,
        **extra: Any,
    ) -> ProblemDetails:
        return cls(
            type=type_uri or f"urn:geoai:error:{status_code}",
            title=title or get_http_title(status_code),
            status=status_code,
            detail=detail,
            instance=instance,
            **extra,
        )

    def to_response_dict(self) -> dict[str, Any]:
        """Return canonical dict with both top-level RFC 7807 fields and nested error block."""
        data: dict[str, Any] = {
            "type": self.type,
            "title": self.title,
            "status": self.status,
            "detail": self.detail,
            "instance": self.instance,
        }
        data["error"] = {
            "type": self.type,
            "title": self.title,
            "status": self.status,
            "detail": self.detail,
            "instance": self.instance,
        }
        return data
